import { 
    ICoinsConfiguration, 
    ICoinsObject, 
    IKeyZonesConfiguration, 
    ILiquidityConfiguration, 
    ITrendStateConfiguration, 
    IWindowStateConfiguration 
} from "../market-state";
import { IPositionStrategy } from "../position";
import { ISignalPolicies } from "../signal";





// Service
export interface ICampaignService {
    // Properties
    balance: IAccountBalance,

    // Initializer
    initialize(): Promise<void>,
    stop(): void,

    // Campaign Creation
    buildCampaignSkeleton(): Promise<ICampaignRecord>,
    createCampaign(campaign: ICampaignRecord): Promise<void>,

    // Futures Account Balance
    syncBalance(): Promise<void>,
}





// Validations
export interface ICampaignValidations {
    // Campaign Creation
    canCampaignSkeletonBeBuilt(active: ICampaignRecord|undefined, balance: IAccountBalance): void,
    canCampaignBeCreated(
        active: ICampaignRecord|undefined, 
        balance: IAccountBalance, 
        existingShareHolders: ICampaignShareHolder[],
        newCampaign: ICampaignRecord
    ): void,
    validateBalanceBasicProperties(balance: IAccountBalance): void,
}






// Model
export interface ICampaignModel {
    

    // Income Records Management
    saveIncomeRecords(records: IAccountIncomeRecord[]): Promise<void>,
    getLastIncomeRecordTimestamp(incomeType: IAccountIncomeType): Promise<number|undefined>,
}








/************
 * Campaign *
 ************/






/**
 * Campaign Record
 * The main object containing all the information related to a campaign.
 */
export interface ICampaignRecord {
    // Universal Unique Identifier
    id: string,

    // The name and a description/terms of the campaign
    name: string,
    description: string,

    // Date Range
    start: number,
    end: number|undefined, // Only populated once a campaign is closed

    // The maximum loss% allowed before disabling trading (This value must be a negative number)
    max_loss: number,

    // The snapshot of the futures account balance when the camapaign was started
    performance: ICampaignPerformance,

    // The list of campaign shareholders
    shareholders: ICampaignShareHolder[],

    // The shareholder's data related to the campaign
    shareholders_data: IShareHoldersData
}




/**
 * Campaign Performance
 * The object containing all the information regarding the operations of a campaign.
 * All values except for initial_balance change constantly until the campaign is closed.
 */
export interface ICampaignPerformance {
    // The snapshot of the futures account balance when the campaign was created
    initial_balance: number,

    // The current futures account balance
    current_balance: number,

    // The accumulated ROI%. This value changes until the campaign is closed
    roi: number,

    // The accumulated PNL. This value changes until the campaign is closed
    pnl: number,

    // The total profit generated by Epoca, derived from the shareholders' profit splits
    epoca_profit: number
}




/**
 * Campaign Shareholder
 * All registered users are potential shareholders. Their participation
 * is determined by their shares on a given campaign.
 */
export interface ICampaignShareHolder {
    // The user's ID
    uid: string,

    // The user's nickname, derived from their email
    nickname: string
}



/**
 * ShareHolder Data
 * The object containing all the essential information for the shareholders. 
 */
export interface IShareHoldersData {[uid: string]: IShareHolderData};
export interface IShareHolderData {
    // The original balance the user had when the campaign was created
    original_balance: number,

    /**
     * The number of shares accumulated based on the user's original_balance 
     * and the campaign's initial_balance.
     */
    shares: number,

    // The percent of the profit that will be assigned to the user
    profit_split: number,

    // The accumulated ROI%. This value changes until the campaign is closed
    roi: number,

    // The accumulated PNL. This value changes until the campaign is closed
    pnl: number,

    // The original balance + the PNL. This value changes until the campaign is closed
    balance: number
}







/**
 * Campaign Headline
 * A minified object containing only essential information.
 */
export interface ICampaignHeadline {
    // Universal Unique Identifier
    id: string,

    // Date Range
    start: number,
    end: number|undefined,
}











/**
 * Campaign Configuration Snapshots
 * When a campaign is created, the configuration snapshots for
 * the core modules are stored so they can be compared later on.
 */
export interface ICampaignConfigurationsSnapshot {
    // Window Configuration
    window: IWindowStateConfiguration,

    // Trend Configuration
    trend: ITrendStateConfiguration,

    // Liquidity Configuration
    liquidity: ILiquidityConfiguration,

    // KeyZones Configuration
    keyzones: IKeyZonesConfiguration,

    // Coins Configuration
    coins: ICoinsConfiguration,
    installed_coins: ICoinsObject,

    // Position Strategy Configuration
    strategy: IPositionStrategy,

    // Signal Policies
    signal_policies: ISignalPolicies
}



















/***********
 * Balance *
 ***********/



/**
 * Account Balance
 * In Epoca, the balance is always referring to USDT and is always extracted
 * fresh from Binance's API.
 */
export interface IAccountBalance {
    // The available balance in the account that can be used to initialize positions
    available: number,

    // The balance that has been allocated to positions (margin)
    on_positions: number,

    // The total balance in the account including unrealized pnl
    total: number,

    // The time in which the balance data was last updated by Binance
    ts: number
}












/**********
 * Income *
 **********/






/**
 * Account Income Record
 * Whenever a campaign is active, the account's income is constantly synced
 * with the balance. Individual records are stored in the database for
 * deeper analysis.
 */
export type IAccountIncomeType = "REALIZED_PNL"|"COMMISSION"|"FUNDING_FEE";
export interface IAccountIncomeRecord {
    // The unique identifier of the transaction
    id: string,

    // The time in milliseconds at which the income was generated
    t: number,

    // The symbol that generated the income
    s: string,

    // The type of income
    it: IAccountIncomeType,

    // The income generated by the transaction (can be a negative value)
    v: number
}
